Add annonce
WildCodeSchool/2103-lille-js-p3-immosup-backend pull request #2
Opened 2021-06-16 13:30 UTC by Sofiaboud

Routes

2021-06-17 07:07 UTC, ThomasSupervil approved these changes, later dismissed
seems good

2021-06-17 12:41 UTC, LoicBrassart commented
SM validation before you call for me plz!

2021-06-17 12:43 UTC, ThomasSupervil submitted a review, later dismissed
good now

2021-06-17 18:03 UTC, LoicBrassart requested changes
Some Evils and a decision to make

2021-06-17 18:03 UTC, LoicBrassart commented on package.json
> +    "start": "nodemon app.js",
Nope (won't work once deployed)

2021-06-17 18:03 UTC, LoicBrassart commented on package.json
> +    "nodemon": "^2.0.7"
Nodemon should be a **dev**Dependancies

2021-06-17 18:03 UTC, LoicBrassart commented on models/annonce.js
> +  }).validate(body, { abortEarly: false }).error;
If you wanna use `Joi`, I want your backend validation criteria to match your db requirements exactly (types of fields, data length, etc) on the whole project, and every field transmitted by the frontend bia any mean will have to go through a strict Joi validation process.
I'll take the merging of this PR into `dev` as a collective (both groups!) agreement to abide by this new standard

2021-06-23 09:45 UTC, ThomasSupervil approved these changes, later dismissed
✌️

2021-06-24 09:07 UTC, LoicBrassart commented
Solve conflicts before you ask for my review please

2021-06-24 09:16 UTC, ThomasSupervil submitted a review, later dismissed
resolve conflict

2021-06-24 11:24 UTC, ThomasSupervil approved these changes, later dismissed
good

2021-06-30 09:39 UTC, LoicBrassart requested changes
Don't use "SELECT *"

2021-06-30 09:39 UTC, LoicBrassart commented on models/annonce.js
> +  const sql = 'SELECT * FROM accomodations';
No "SELECT *"

2021-06-30 09:39 UTC, LoicBrassart commented on models/annonce.js
> +  const sql = 'SELECT * FROM accomodations WHERE id = ?';
No "SELECT *"

2021-07-02 14:30 UTC, ThomasSupervil approved these changes
No "SELECT *" at the horizon

2021-07-03 07:55 UTC, LoicBrassart approved these changes
SnE

2021-07-03 16:28 UTC, merged