Mailback
WildCodeSchool/2103-lille-js-p3-immosup-backend pull request #5
Opened 2021-06-23 07:42 UTC by Hochart-dev

add backend for Sending Mail.

2021-06-23 07:51 UTC, ThomasSupervil approved these changes, later dismissed
Seems good

2021-06-24 09:08 UTC, LoicBrassart commented
Solve conflicts please

2021-06-24 09:22 UTC, ThomasSupervil approved these changes, later dismissed
resolve conflicts

2021-06-24 09:37 UTC, ThomasSupervil submitted a review, later dismissed
🥸

2021-06-30 09:41 UTC, LoicBrassart requested changes
A bit of useless code to delete

2021-06-30 09:41 UTC, LoicBrassart commented on conf.js
> +});
Useless, remove this

2021-07-01 09:47 UTC, LoicBrassart approved these changes
SnE!

2021-07-02 10:03 UTC, ThomasSupervil approved these changes
goody

2021-07-02 10:03 UTC, merged