12 accommodation page fav
WildCodeSchool/2103-lille-js-p3-immosup-backend pull request #6
Opened 2021-06-23 08:31 UTC by RobinDela

2021-06-23 09:18 UTC, bdtkevin requested changes

2021-06-23 09:18 UTC, bdtkevin commented on models/favorites.js
> +group by id
Strange indentation 🤣

2021-06-23 09:26 UTC, bdtkevin submitted a review, later dismissed
👍

2021-06-24 09:10 UTC, LoicBrassart commented
Please solve conflicts

2021-06-24 10:45 UTC, bdtkevin submitted a review, later dismissed

2021-06-30 09:45 UTC, LoicBrassart requested changes
Stop using "SELECT *"

2021-06-30 09:45 UTC, LoicBrassart commented on models/favorites.js
> +  select accomodations.*, (
Don't use "SELECT *"

2021-07-03 07:56 UTC, LoicBrassart commented
No validation from the SM

2021-07-03 16:29 UTC, bdtkevin requested changes
SELECT *

2021-07-05 08:11 UTC, bdtkevin approved these changes
👍🏼👍🏼

2021-07-05 08:58 UTC, LoicBrassart approved these changes
NmE

2021-07-08 06:39 UTC, merged